### ISSUE TITLE
Depends on version of lolcommits that doesn't exist

### ISSUE THREAD

**Issue by Ruxton** [lolcommits/lolcommits-loltext#1]
Recent changes in the last month to master have introduced new hooks and it's not even bumped to 0.9.5 in the one branch they exist in.

loltext should either have a development branch with this change or lolcommits should get those hook changes out of the extract-twitter-plugin branch and into master.

**Comment by matthutchinson** [comment]
Sorry about the delay on this.. hopefully this weekend will sort it out.

**Comment by matthutchinson** [comment]
Fixed 👍
